package com.learning.wayfind;

/**
 *
 * Piotr Konkol
 * 2026
 */
public class MapGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MapGUI.class.getName());
    
    private RouteManager routeManager = new RouteManager();
    private java.util.HashMap<Integer, Street> streetMap = new java.util.HashMap<>();
    /**
     * Creates new form MapGUI
     */
    public MapGUI() {
        initComponents();
        loadStreets();
    }
    private void loadStreets() {
    streetMap.put(1,  new Street("Mayor Street Lower", 1));
    streetMap.put(2,  new Street("Common Street", 2));
    streetMap.put(3,  new Street("Clarion Quay", 3));
    streetMap.put(4,  new Street("Alderman Way", 4));
    streetMap.put(5,  new Street("Guild Street", 5));
    streetMap.put(6,  new Street("Excise Walk", 6));
    streetMap.put(7,  new Street("North Wall Quay", 7));
    streetMap.put(8,  new Street("Sean O'Casey Bridge", 8));
    streetMap.put(9,  new Street("City Quay", 9));
    streetMap.put(10, new Street("Prince's Street South", 10));
    streetMap.put(11, new Street("Lombard Street East", 11));
    streetMap.put(12, new Street("Dowling's Court", 12));
    streetMap.put(13, new Street("Townsend Street", 13));
    streetMap.put(14, new Street("Ceighton Street", 14));
    streetMap.put(15, new Street("Lime Street", 15));
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        streetNrEntry = new javax.swing.JTextField();
        addBTN = new javax.swing.JButton();
        undoBTN = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        routeInfoBox = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        saveToCSV = new javax.swing.JButton();
        loadFromCSV = new javax.swing.JButton();
        ratingDropdown = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        noteEntry = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        nameEntry = new javax.swing.JTextField();
        clearBTN = new javax.swing.JButton();
        walkRad = new javax.swing.JRadioButton();
        accessRad = new javax.swing.JRadioButton();
        rampsCheck = new javax.swing.JCheckBox();
        terrainDropdown = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/numberedAndLegendedMap.png"))); // NOI18N
        jLabel1.setText(" ");

        jLabel3.setText("Map Menu");

        jLabel4.setText("Enter street number:");

        addBTN.setBackground(new java.awt.Color(153, 255, 153));
        addBTN.setText("Add");
        addBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBTNActionPerformed(evt);
            }
        });

        undoBTN.setBackground(new java.awt.Color(153, 204, 255));
        undoBTN.setText("Undo");
        undoBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                undoBTNActionPerformed(evt);
            }
        });

        routeInfoBox.setColumns(20);
        routeInfoBox.setRows(5);
        jScrollPane1.setViewportView(routeInfoBox);

        jLabel2.setText("Current route info:");

        saveToCSV.setText("Save to CSV");
        saveToCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveToCSVActionPerformed(evt);
            }
        });

        loadFromCSV.setText("Load from CSV");
        loadFromCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadFromCSVActionPerformed(evt);
            }
        });

        ratingDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        jLabel5.setText("Rating:");

        jLabel6.setText("Note:");

        noteEntry.setText(" ");
        noteEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noteEntryActionPerformed(evt);
            }
        });

        jLabel7.setText("Name:");

        nameEntry.setText(" ");
        nameEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameEntryActionPerformed(evt);
            }
        });

        clearBTN.setText("Clear");
        clearBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBTNActionPerformed(evt);
            }
        });

        buttonGroup.add(walkRad);
        walkRad.setSelected(true);
        walkRad.setText("For walking");
        walkRad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                walkRadActionPerformed(evt);
            }
        });

        buttonGroup.add(accessRad);
        accessRad.setText("Accessible");

        rampsCheck.setText("Has ramps?");

        terrainDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Asphalt", "Cobblestone", "Steep", "Unpaved" }));

        jLabel8.setText("Main terrain:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(138, 138, 138)
                                .addComponent(saveToCSV, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ratingDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(undoBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(addBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                                .addComponent(streetNrEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(loadFromCSV)
                                                .addComponent(nameEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(78, 78, 78)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(clearBTN)
                                        .addGap(27, 27, 27))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(walkRad)
                                            .addGap(18, 18, 18)
                                            .addComponent(accessRad)
                                            .addGap(1, 1, 1))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel8))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(terrainDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(rampsCheck))
                                                .addComponent(noteEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(streetNrEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addBTN)
                            .addComponent(undoBTN))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(clearBTN))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(loadFromCSV)
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(ratingDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(noteEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(terrainDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rampsCheck)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(walkRad)
                    .addComponent(accessRad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(saveToCSV)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBTNActionPerformed
    String input = streetNrEntry.getText().trim();
    if (input.isEmpty()){ 
        return;
    }
    try {
        int id = Integer.parseInt(input);
        Street street = streetMap.get(id);
        if (street == null) {
            routeInfoBox.append("Invalid number, try 1-15\n");
        } else {
            routeManager.addStreetToRoute(street);
            routeInfoBox.append(street.toString() + "\n");
        }
    } catch (NumberFormatException e) {
        routeInfoBox.append("Please enter a number\n");
    }
    streetNrEntry.setText("");
    streetNrEntry.requestFocus();
    }//GEN-LAST:event_addBTNActionPerformed

    private void undoBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_undoBTNActionPerformed
    if (routeManager.getCurrentRoute().isEmpty()) {
        routeInfoBox.append("Nothing to undo\n");
        return;
    }
    routeManager.undoLastStreet();
    routeInfoBox.setText("");
    routeInfoBox.append(routeManager.getCurrentRouteDisplay());
    }//GEN-LAST:event_undoBTNActionPerformed

    private void saveToCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveToCSVActionPerformed
    String name = nameEntry.getText().trim();
    String note = noteEntry.getText().trim();
    int rating = Integer.parseInt((String) ratingDropdown.getSelectedItem());

    if (name.isEmpty()) {
        routeInfoBox.append("Please enter a route name\n");
        return;
    }
    if (routeManager.getCurrentRoute().isEmpty()) {
        routeInfoBox.append("No streets in route to save\n");
        return;
    }

    Route route;
    if (accessRad.isSelected()) {
        AccessibleRoute ar = new AccessibleRoute(name, name);
        ar.setHasRamps(rampsCheck.isSelected());
        ar.setRating(rating);
        ar.setNote(note);
        routeInfoBox.append("Difficulty: " + ar.calcDifficulty() + "/10\n");
        route = ar;
    } else {
        WalkingRoute wr = new WalkingRoute(name, name);
        wr.addTerrain((String) terrainDropdown.getSelectedItem());
        wr.setRating(rating);
        wr.setNote(note);
        routeInfoBox.append("Difficulty: " + wr.calcDifficulty() + "/10\n");
        route = wr;
    }

    routeManager.addRoute(name, route);
    routeManager.saveToCSV(name, rating, note, route.calcDifficulty());
    routeInfoBox.append("Route saved: " + name + "\n");

    nameEntry.setText("");
    noteEntry.setText("");
    ratingDropdown.setSelectedIndex(0);
    }//GEN-LAST:event_saveToCSVActionPerformed

    private void loadFromCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadFromCSVActionPerformed
    String filename = nameEntry.getText().trim() + ".csv";
    String result = routeManager.loadFromCSV(filename);
    routeInfoBox.setText("");
    routeInfoBox.append(result);
    }//GEN-LAST:event_loadFromCSVActionPerformed

    private void noteEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noteEntryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noteEntryActionPerformed

    private void nameEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameEntryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameEntryActionPerformed

    private void clearBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBTNActionPerformed
    routeManager.clearCurrentRoute();
    routeInfoBox.setText("");
    }//GEN-LAST:event_clearBTNActionPerformed

    private void walkRadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_walkRadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_walkRadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MapGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton accessRad;
    private javax.swing.JButton addBTN;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JButton clearBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton loadFromCSV;
    private javax.swing.JTextField nameEntry;
    private javax.swing.JTextField noteEntry;
    private javax.swing.JCheckBox rampsCheck;
    private javax.swing.JComboBox<String> ratingDropdown;
    private javax.swing.JTextArea routeInfoBox;
    private javax.swing.JButton saveToCSV;
    private javax.swing.JTextField streetNrEntry;
    private javax.swing.JComboBox<String> terrainDropdown;
    private javax.swing.JButton undoBTN;
    private javax.swing.JRadioButton walkRad;
    // End of variables declaration//GEN-END:variables
}
